let significantDates = [
    "55 BC",
    "AD 43",
    "AD 410"
];

let englishCounties = [
    "Bedfordshire",
    "Berkshire",
    "Bristol",
    "Buckinghamshire",
    "Cambridgeshire",
    "Cheshire",
    "Cornwall",
    "Cumbria",
    "Derbyshire",
    "Devon",
    "Dorset",
    "Durham",
    "East Sussex",
    "Essex",
    "Gloucestershire",
    "Greater London",
    "Greater Manchester",
    "Hampshire",
    "Herefordshire",
    "Hertfordshire",
    "Isle of Wight",
    "Kent",
    "Lancashire",
    "Leicestershire",
    "Lincolnshire",
    "Merseyside",
    "Norfolk",
    "North Yorkshire",
    "Northamptonshire",
    "Northumberland",
    "Nottinghamshire",
    "Oxfordshire",
    "Rutland",
    "Shropshire",
    "Somerset",
    "South Yorkshire",
    "Staffordshire",
    "Suffolk",
    "Surrey",
    "Tyne and Wear",
    "Warwickshire",
    "West Midlands",
    "Westmorland",
    "West Sussex",
    "West Yorkshire",
    "Wiltshire",
    "Worcestershire"
];

let ukIndividualIslands = [
    "The Isle of Wight",
    "Skye",
    "Lewis",
    "Harris",
    "Orkney",
    "Arran",
    "Mull",
    "Jura",
    "Iona",
    "Shetland",
    "Anglesey",
];

let europeanCountries = [
    "The United Kingdom",
    "The Republic of Ireland",
    "France",
    "Spain",
    "Portugal",
    "Italy",
    "Germany",
    "Belgium",
    "The Netherlands",
    "Denmark",
    "Iceland",
    "Sweden",
    "Denmark",
    "Norway",
    "Finland",
];